"""Configurações centrais do Tech Challenge Fase 3."""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
FIGURES_DIR = OUTPUTS_DIR / "figures"
MODELS_DIR = OUTPUTS_DIR / "models"
REPORTS_DIR = OUTPUTS_DIR / "reports"

AIRLINES_PATH = DATA_DIR / "airlines.csv"
AIRPORTS_PATH = DATA_DIR / "airports.csv"
FLIGHTS_PATH = DATA_DIR / "flights.csv"
DATA_DICTIONARY_GLOB = "dicionario_dados_flights*"

RANDOM_STATE = 42
TEST_SIZE = 0.25
DELAY_THRESHOLD_MINUTES = 15
MIN_GROUP_FLIGHTS = 1000
DEFAULT_SAMPLE_SIZE = 250_000

LEAKAGE_COLUMNS = [
    "ARRIVAL_DELAY",
    "ARRIVAL_TIME",
    "ELAPSED_TIME",
    "AIR_TIME",
    "TAXI_IN",
    "WHEELS_ON",
    "AIR_SYSTEM_DELAY",
    "SECURITY_DELAY",
    "AIRLINE_DELAY",
    "LATE_AIRCRAFT_DELAY",
    "WEATHER_DELAY",
    "CANCELLATION_REASON",
    "DEPARTURE_TIME",
    "DEPARTURE_DELAY",
    "TAXI_OUT",
    "WHEELS_OFF",
]

MODEL_FEATURES = [
    "MONTH",
    "DAY",
    "DAY_OF_WEEK",
    "AIRLINE",
    "ORIGIN_AIRPORT",
    "DESTINATION_AIRPORT",
    "SCHEDULED_DEPARTURE_MINUTES",
    "SCHEDULED_ARRIVAL_MINUTES",
    "SCHEDULED_TIME",
    "DISTANCE",
    "DEPARTURE_PERIOD",
    "DISTANCE_CATEGORY",
    "IS_BUSY_ROUTE",
]

CATEGORICAL_FEATURES = [
    "AIRLINE",
    "ORIGIN_AIRPORT",
    "DESTINATION_AIRPORT",
    "DEPARTURE_PERIOD",
    "DISTANCE_CATEGORY",
    "IS_BUSY_ROUTE",
]

NUMERIC_FEATURES = [
    "MONTH",
    "DAY",
    "DAY_OF_WEEK",
    "SCHEDULED_DEPARTURE_MINUTES",
    "SCHEDULED_ARRIVAL_MINUTES",
    "SCHEDULED_TIME",
    "DISTANCE",
]
